#!/usr/bin/env python3
"""Emit the parity figure and tables from the sweep's JSON.

Two bases are always reported side by side. *Total* is wall clock for the whole
operation. *Corrected* subtracts the measured fixed cost `c` -- the no-op fetch,
which transfers nothing, so whatever it costs is process spawn, protocol
preamble and server dispatch rather than work on bytes. The two transports have
very different `c` (SafeHub ~20 ms, git ~48 ms), so a ratio of totals reports
that difference as much as it reports encryption. Showing only totals would
credit SafeHub with an advantage it has not earned; showing only corrected
figures would hide what a user actually waits for.

Writes:
  paper/figures/parity-plots.tex          groupplot, total (solid) vs corrected (dashed)
  paper/figures/parity-latency-table.tex  push/pull, both bases
  <json dir>/parity-summary.csv           flat one-row-per-size table
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    ROOT, "code/eval/published/parity-latest.json")
FIG = os.path.join(ROOT, "paper", "figures")


def load():
    d = json.load(open(SRC))
    rows = [s for s in d["sizes"] if s.get("status") == "measured"]
    rows.sort(key=lambda s: s["size_mb"])
    return d, rows


def coords(rows, fn, nd=2):
    """Coordinate list against repository size (clone and storage)."""
    return " ".join(f"({s['size_mb']},{round(fn(s), nd)})" for s in rows)


def dcoords(rows, fn, nd=2):
    """Coordinate list against data moved per operation (push and pull).

    A push or pull transfers one delta, not the repository, so plotting either
    against repository size would misstate what the x-axis means. Clone and
    storage do span the whole repository and keep that axis.
    """
    return " ".join(
        f"({round(s['delta_bytes'] / 1048576, 3)},{round(fn(s), nd)})" for s in rows)


def plots(rows):
    sit_push = dcoords(rows, lambda s: s["safehub"]["push_ms"]["mean"])
    git_push = dcoords(rows, lambda s: s["git"]["push_ms"]["mean"])
    sit_pull = dcoords(rows, lambda s: s["safehub"]["pull_ms"]["mean"])
    git_pull = dcoords(rows, lambda s: s["git"]["pull_ms"]["mean"])
    sit_pullc = dcoords(rows, lambda s: s["corrected"]["sit_pull_work_ms"])
    git_pullc = dcoords(rows, lambda s: s["corrected"]["git_pull_work_ms"])
    sit_clone = coords(rows, lambda s: s["safehub"]["clone_cold_ms"] / 1000)
    git_clone = coords(rows, lambda s: s["git"]["clone_packed_ms"] / 1000)
    git_cloneu = coords(rows, lambda s: s["git"]["clone_cold_ms"] / 1000)
    sit_store = coords(rows, lambda s: s["safehub"]["server_bytes"] / 1e6, 1)
    git_store = coords(rows, lambda s: s["git"]["server_bytes_packed"] / 1e6, 1)

    tpl = r"""% Generated by scripts/make_parity_figures.py -- do not edit by hand.
\definecolor{sitcol}{HTML}{1B6CA8}
\definecolor{sitcorr}{HTML}{5BA7D9}
\definecolor{gitcol}{HTML}{C0392B}
\definecolor{gitcorr}{HTML}{E8886B}
\definecolor{gitloose}{HTML}{7D3C98}
\begin{figure}[t]
\centering
\begin{tikzpicture}
\begin{groupplot}[
  group style={group size=2 by 2, horizontal sep=5mm, vertical sep=12mm},
  width=0.58\columnwidth, height=4.6cm,
  tick label style={font=\tiny},
  label style={font=\tiny}, xlabel shift=-4pt,
  legend style={font=\tiny, draw=none, fill=none,
    column sep=2.2ex, /tikz/every even column/.append style={column sep=1.2ex}},
  grid=major, grid style={gray!20},
]

\nextgroupplot[ylabel={push (ms)}, xlabel={data per operation (MB)},
  xmin=0, xmax=5.2, legend to name=parityleg, legend columns=3]
\addplot[thick, sitcol,  mark=*,       mark size=1.2] coordinates {@SIT_PUSH@};
\addlegendentry{\texttt{sit} total}
\addplot[thick, gitcol,  mark=square*, mark size=1.2] coordinates {@GIT_PUSH@};
\addlegendentry{git total}
\addlegendimage{thick, sitcorr, dashed, mark=o, mark size=1.2}
\addlegendentry{\texttt{sit} corrected}
\addlegendimage{thick, gitcorr, dashed, mark=square, mark size=1.2}
\addlegendentry{git corrected}
\addlegendimage{thick, gitloose, dotted, mark=triangle, mark size=1.2}
\addlegendentry{git unpacked}

\nextgroupplot[ylabel={pull (ms)}, xlabel={data per operation (MB)},
  xmin=0, xmax=5.2]
\addplot[thick, sitcol,  mark=*,       mark size=1.2] coordinates {@SIT_PULL@};
\addplot[thick, gitcol,  mark=square*, mark size=1.2] coordinates {@GIT_PULL@};
\addplot[thick, sitcorr, dashed, mark=o,      mark size=1.2] coordinates {@SIT_PULLC@};
\addplot[thick, gitcorr, dashed, mark=square, mark size=1.2] coordinates {@GIT_PULLC@};

\nextgroupplot[ylabel={clone (sec)}, xlabel={repository (MB)},
  xmin=0, xmax=520]
\addplot[thick, sitcol,   mark=*,        mark size=1.2] coordinates {@SIT_CLONE@};
\addplot[thick, gitcol,   mark=square*,  mark size=1.2] coordinates {@GIT_CLONE@};
\addplot[thick, gitloose, dotted, mark=triangle, mark size=1.2] coordinates {@GIT_CLONEU@};

\nextgroupplot[ylabel={stored (MB)}, xlabel={repository (MB)},
  xmin=0, xmax=520]
\addplot[thick, sitcol, mark=*,       mark size=1.2] coordinates {@SIT_STORE@};
\addplot[thick, gitcol, mark=square*, mark size=1.2] coordinates {@GIT_STORE@};

\end{groupplot}
\end{tikzpicture}
\\[3pt]
\ref{parityleg}
\caption{\Safehub against plain Git over twelve repositories of $5$--$500$\,MB,
$100$ pushes each. Push and pull are plotted against the bytes each operation
moves; clone and storage span the whole repository. Corrected pull subtracts
each system's own no-op fetch. Push is shown as totals, having no measured
no-op counterpart. Clone shows Git both \texttt{gc}-packed and as $100$ pushes
leave it. Git is served over native \texttt{git://}.}
\label{fig:parity}
\end{figure}
"""
    for key, val in (("SIT_PUSH", sit_push), ("GIT_PUSH", git_push),
                     ("SIT_PULL", sit_pull), ("GIT_PULL", git_pull),
                     ("SIT_PULLC", sit_pullc), ("GIT_PULLC", git_pullc),
                     ("SIT_CLONE", sit_clone), ("GIT_CLONE", git_clone),
                     ("GIT_CLONEU", git_cloneu),
                     ("SIT_STORE", sit_store), ("GIT_STORE", git_store)):
        tpl = tpl.replace("@" + key + "@", val)
    return tpl


def latency_table(rows):  # retained: fig:parity now carries this data
    body = []
    for s in rows:
        c, r = s["corrected"], s["ratio"]
        # Only pull is corrected. The measured floor (fixed_cost_ms) is a no-op
        # *fetch*: the same operation a pull performs, minus the bytes, so
        # subtracting it isolates pull's byte-dependent work. There is no
        # corresponding no-op *push* measurement in the artifact, and a fetch
        # floor is not a floor for push -- over HTTP git's no-op fetch (64-74ms)
        # exceeds its entire push at the three smallest repositories. Reporting
        # a "corrected push" against that floor would put a number on a
        # subtraction the data does not support, so the group is not emitted.
        def num(v, prec=2):
            return "--" if v is None else f"{v:.{prec}f}"
        body.append(
            f"{s['size_mb']} & {s['delta_bytes']/1048576:.2f} & "
            f"{s['safehub']['push_ms']['mean']:.0f} & "
            f"{s['git']['push_ms']['mean']:.0f} & {num(r.get('push_mean'))} & "
            f"{s['safehub']['pull_ms']['mean']:.0f} & "
            f"{s['git']['pull_ms']['mean']:.0f} & {num(r.get('pull_mean'))} & "
            f"{num(c.get('sit_pull_work_ms'), 0)} & {num(c.get('git_pull_work_ms'), 0)} & "
            f"{num(r.get('pull_work'))} \\\\")
    return r"""% Generated by scripts/make_parity_figures.py -- do not edit by hand.
\begin{table}[t]
\centering
\caption{Push and pull latency, mean of 100 operations. \emph{Repo} and
\emph{data/op} are in MB, each operation moving one hundredth of the
repository. \emph{Pull, corrected}
subtracts each system's own measured no-op fetch,
which is the same operation carrying no bytes and so isolates byte-dependent
work. Push is reported uncorrected: the artifact measures no no-op push, and
git's no-op fetch exceeds its whole push below $100$\,MB, so it is not a floor
for push.}
\label{tab:parity-latency}
\footnotesize
\setlength{\tabcolsep}{2.6pt}
\begin{tabular}{@{}rr rrr rrr rrr@{}}
\toprule
& & \multicolumn{3}{c}{push (ms)} & \multicolumn{3}{c}{pull (ms)}
& \multicolumn{3}{c}{pull, corrected (ms)} \\
\cmidrule(lr){3-5}\cmidrule(lr){6-8}\cmidrule(lr){9-11}
repo & data/op & \texttt{sit} & git & $\times$ & \texttt{sit} & git & $\times$
& \texttt{sit} & git & $\times$ \\
\midrule
""" + "\n".join(body) + r"""
\bottomrule
\end{tabular}
\end{table}
"""


def clone_table(rows):  # retained: fig:parity now carries this data
    body = []
    for s in rows:
        sh, g, r = s["safehub"], s["git"], s["ratio"]
        body.append(
            f"{s['size_mb']} & {sh['clone_cold_ms']/1000:.2f} & "
            f"{g['clone_packed_ms']/1000:.2f} & {r['clone_vs_packed']:.1f} & "
            f"{sh['fixed_cost_ms']:.0f} & {g['fixed_cost_ms']:.0f} & "
            f"{sh['server_bytes']/1e6:.0f} & {g['server_bytes_packed']/1e6:.0f} & "
            f"{r['storage_vs_packed']:.2f} \\\\")
    return r"""% Generated by scripts/make_parity_figures.py -- do not edit by hand.
\begin{table}[t]
\centering
\caption{Clone, no-op fetch floor, and server storage; \emph{repo} in MB.}
\label{tab:parity-clone}
\footnotesize
\begin{tabular}{r rrr rr rrr}
\toprule
& \multicolumn{3}{c}{clone (sec)} & \multicolumn{2}{c}{no-op fetch (ms)}
& \multicolumn{3}{c}{stored (MB)} \\
\cmidrule(lr){2-4}\cmidrule(lr){5-6}\cmidrule(lr){7-9}
repo & \texttt{sit} & git & $\times$ & \texttt{sit} & git & \texttt{sit} & git & $\times$ \\
\midrule
@BODY@
\bottomrule
\end{tabular}
\end{table}
""".replace("@BODY@", "\n".join(body))


CSV_COLS = [
    "size_mb", "delta_bytes", "data_per_op_mb", "pushes", "identical_content",
    "sit_push_ms", "git_push_ms", "push_ratio",
    "sit_push_work_ms", "git_push_work_ms", "push_work_ratio",
    "sit_pull_ms", "git_pull_ms", "pull_ratio",
    "sit_pull_work_ms", "git_pull_work_ms", "pull_work_ratio",
    "sit_fixed_ms", "git_fixed_ms",
    "sit_clone_ms", "git_clone_packed_ms", "git_clone_loose_ms", "clone_ratio",
    "sit_bytes", "git_bytes_packed", "storage_ratio",
    "sit_headlog_bytes", "git_gc_ms",
    "sit_push_slope", "git_push_slope", "sit_pull_slope", "git_pull_slope",
]


def csv_rows(rows):
    out = [",".join(CSV_COLS)]
    for s in rows:
        sh, g, c, r = s["safehub"], s["git"], s["corrected"], s["ratio"]
        vals = [
            s["size_mb"], s["delta_bytes"], round(s["delta_bytes"]/1048576, 3),
            s["pushes"], s.get("identical_content"),
            sh["push_ms"]["mean"], g["push_ms"]["mean"], r["push_mean"],
            c["sit_push_work_ms"], c["git_push_work_ms"], r["push_work"],
            sh["pull_ms"]["mean"], g["pull_ms"]["mean"], r["pull_mean"],
            c["sit_pull_work_ms"], c["git_pull_work_ms"], r["pull_work"],
            sh["fixed_cost_ms"], g["fixed_cost_ms"],
            sh["clone_cold_ms"], g["clone_packed_ms"], g["clone_cold_ms"],
            r["clone_vs_packed"],
            sh["server_bytes"], g["server_bytes_packed"], r["storage_vs_packed"],
            sh["headlog_bytes"], g["gc_ms"],
            sh["push_ms"]["slope_ms_per_iter"], g["push_ms"]["slope_ms_per_iter"],
            sh["pull_ms"]["slope_ms_per_iter"], g["pull_ms"]["slope_ms_per_iter"],
        ]
        out.append(",".join(str(v) for v in vals))
    return "\n".join(out) + "\n"


def main():
    d, rows = load()
    if not rows:
        sys.exit("no measured sizes in " + SRC)
    os.makedirs(FIG, exist_ok=True)
    for name, text in (("parity-plots.tex", plots(rows)),
                       ):
        with open(os.path.join(FIG, name), "w") as fh:
            fh.write(text)
        print("wrote paper/figures/" + name)
    csv_path = os.path.join(os.path.dirname(SRC), "parity-summary.csv")
    with open(csv_path, "w") as fh:
        fh.write(csv_rows(rows))
    print("wrote " + os.path.relpath(csv_path, ROOT))
    print(f"{len(rows)} sizes: {', '.join(str(s['size_mb']) for s in rows)} MB")
    m = d.get("machine", {})
    print("machine:", m.get("os"), m.get("arch"), "| load", m.get("load_before"))


if __name__ == "__main__":
    main()
