#!/usr/bin/env python3
"""Emit SafeHub vs Git comparison figures for eval fixtures that already
carry matched plain-Git baselines.

Writes:
  paper/figures/realrepo-baseline-plots.tex
  paper/figures/additive-baseline-plots.tex
  paper/figures/encrypted-git-baseline-plots.tex
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUB = os.path.join(ROOT, "code/eval/published")
FIG = os.path.join(ROOT, "paper", "figures")


def med(obj):
    if isinstance(obj, dict):
        return obj["median"]
    return float(obj)


def realrepo_plots():
    d = json.load(open(os.path.join(PUB, "realrepo-scale-latest.json")))
    rows = d.get("measured_synthetic_compressible_corpora") or []
    rows = [r for r in rows if r.get("status") == "measured"]
    rows = sorted(rows, key=lambda r: r["tree_bytes"])
    if not rows:
        sys.exit("no measured realrepo compressible corpora")
    # x = tree MiB
    xs = [round(r["tree_bytes"] / (1024 * 1024), 1) for r in rows]
    sh_push = " ".join(f"({x},{med(r['safehub_push_ms']):.0f})"
                       for x, r in zip(xs, rows))
    git_push = " ".join(f"({x},{med(r['plain_git_push_ms']):.0f})"
                        for x, r in zip(xs, rows))
    sh_clone = " ".join(f"({x},{med(r['safehub_clone_ms']):.0f})"
                        for x, r in zip(xs, rows))
    git_clone = " ".join(f"({x},{med(r['plain_git_clone_ms']):.0f})"
                         for x, r in zip(xs, rows))
    ct_pack = " ".join(
        f"({x},{r['ciphertext_over_plain_git_pack']:.3f})"
        for x, r in zip(xs, rows))
    xmax = max(xs) * 1.15
    return r"""% Generated by scripts/make_baseline_figures.py -- do not edit by hand.
\definecolor{sitcol}{HTML}{1B6CA8}
\definecolor{gitcol}{HTML}{C0392B}
\begin{figure*}[t]
\centering
\begin{tikzpicture}
\begin{groupplot}[
  group style={group size=3 by 1, horizontal sep=20mm},
  width=0.28\textwidth, height=0.24\textwidth,
  tick label style={font=\scriptsize}, xlabel shift=-4pt,
  label style={font=\scriptsize}, xlabel shift=-4pt,
  legend style={font=\scriptsize, draw=none, fill=none, column sep=2.2ex},
  grid=major, grid style={gray!20},
  xlabel={working tree (MiB)},
  xmin=0, xmax=@XMAX@,
]

\nextgroupplot[ylabel={push (ms)}, ymin=0,
  title={\scriptsize (a) push},
  legend to name=rrleg, legend columns=2]
\addplot[thick, sitcol, mark=*,       mark size=1.4] coordinates {@SH_PUSH@};
\addlegendentry{SafeHub}
\addplot[thick, gitcol, mark=square*, mark size=1.4] coordinates {@GIT_PUSH@};
\addlegendentry{Git}

\nextgroupplot[ylabel={clone (ms)}, ymin=0,
  title={\scriptsize (b) clone}]
\addplot[thick, sitcol, mark=*,       mark size=1.4] coordinates {@SH_CLONE@};
\addplot[thick, gitcol, mark=square*, mark size=1.4] coordinates {@GIT_CLONE@};

\nextgroupplot[ylabel={ct / git pack}, ymin=0, ymax=1.2,
  title={\scriptsize (c) storage vs pack}]
\addplot[thick, sitcol, mark=*, mark size=1.4] coordinates {@CT_PACK@};

\end{groupplot}
\node[below=7mm of group c2r1.south, anchor=north] {\ref{rrleg}};
\end{tikzpicture}
\caption{Push, clone, and stored size on source-code repositories that
compress well, against plain Git on the same trees. Panel~(c) is server
ciphertext against \texttt{gc}-packed Git. Client and server share one host.}
\label{fig:realrepo-baseline}
\end{figure*}
""".replace("@SH_PUSH@", sh_push).replace("@GIT_PUSH@", git_push).replace(
        "@SH_CLONE@", sh_clone).replace("@GIT_CLONE@", git_clone).replace(
        "@CT_PACK@", ct_pack).replace("@XMAX@", f"{xmax:.1f}")


def additive_plots():
    d = json.load(open(os.path.join(PUB, "additive-scale-latest.json")))
    rows = sorted(d.get("size_ops", []), key=lambda r: r["size_mib"])
    if not rows:
        sys.exit("no additive size_ops")
    for r in rows:
        for k in ("safehub_push_ms_aggregate", "plain_git_incremental_push_ms",
                  "safehub_clone_ms", "plain_git_clone_ms",
                  "rotate_ms", "consolidate_ms"):
            if k not in r:
                sys.exit(f"additive row {r['size_mib']} missing {k}")

    sh_push = " ".join(f"({r['size_mib']},{r['safehub_push_ms_aggregate']})"
                       for r in rows)
    git_push = " ".join(f"({r['size_mib']},{r['plain_git_incremental_push_ms']})"
                        for r in rows)
    sh_clone = " ".join(f"({r['size_mib']},{r['safehub_clone_ms']})"
                        for r in rows)
    git_clone = " ".join(f"({r['size_mib']},{r['plain_git_clone_ms']})"
                         for r in rows)
    rotate = " ".join(f"({r['size_mib']},{r['rotate_ms']})" for r in rows)
    consol = " ".join(f"({r['size_mib']},{r['consolidate_ms']})" for r in rows)
    xmax = max(r["size_mib"] for r in rows) * 1.05

    return r"""% Generated by scripts/make_baseline_figures.py -- do not edit by hand.
\definecolor{sitcol}{HTML}{1B6CA8}
\definecolor{gitcol}{HTML}{C0392B}
\definecolor{rotcol}{HTML}{4A4A4A}
\begin{figure*}[t]
\centering
\begin{tikzpicture}
\begin{groupplot}[
  group style={group size=3 by 1, horizontal sep=20mm},
  width=0.28\textwidth, height=0.24\textwidth,
  tick label style={font=\scriptsize}, xlabel shift=-4pt,
  label style={font=\scriptsize}, xlabel shift=-4pt,
  legend style={font=\scriptsize, draw=none, fill=none, column sep=1.5ex},
  grid=major, grid style={gray!20},
  xlabel={size (MiB)},
  xmin=0, xmax=@XMAX@,
]

\nextgroupplot[ylabel={latency (ms)}, ymin=0,
  title={\scriptsize (a) $N{=}8$ incremental push},
  legend to name=addleg, legend columns=2]
\addplot[thick, sitcol, mark=*,       mark size=1.2] coordinates {@SH_PUSH@};
\addlegendentry{SafeHub}
\addplot[thick, gitcol, mark=square*, mark size=1.2] coordinates {@GIT_PUSH@};
\addlegendentry{Git}

\nextgroupplot[ylabel={clone (ms)}, ymin=0,
  title={\scriptsize (b) clone}]
\addplot[thick, sitcol, mark=*,       mark size=1.2] coordinates {@SH_CLONE@};
\addplot[thick, gitcol, mark=square*, mark size=1.2] coordinates {@GIT_CLONE@};

\nextgroupplot[ylabel={latency (ms)}, ymin=0,
  title={\scriptsize (c) rotate / consolidate}]
\addplot[thick, rotcol, dashed, mark=o, mark size=1.2] coordinates {@ROTATE@};
\addlegendentry{rotate}
\addplot[thick, sitcol, mark=triangle*, mark size=1.3] coordinates {@CONSOL@};
\addlegendentry{consolidate}
\legend{rotate, consolidate}

\end{groupplot}
\node[below=7mm of group c1r1.south, anchor=north] {\ref{addleg}};
\end{tikzpicture}
\caption{Push and clone as a repository grows by eight successive pushes,
against plain Git on the same trees. Panel~(c) has no plain-Git counterpart:
it reports MLS epoch rotation, and a consolidation series that measures
transport throughput on a synthetic payload and is withdrawn as a compaction
measurement (\cref{sec:consolidation}). Client and server share one host.}
\label{fig:additive-baseline}
\end{figure*}
""".replace("@SH_PUSH@", sh_push).replace("@GIT_PUSH@", git_push).replace(
        "@SH_CLONE@", sh_clone).replace("@GIT_CLONE@", git_clone).replace(
        "@ROTATE@", rotate).replace("@CONSOL@", consol).replace(
        "@XMAX@", f"{xmax:.0f}")


def encrypted_git_plots():
    """Retired: superseded by scripts/make_review_figures.py.

    That generator plots all four arms as measured across two fixtures. This
    one assumed git-crypt and git-remote-gcrypt were modelled and expected an
    arm named `sit-safehub`, which the measured harness does not emit.
    """
    raise SystemExit(
        "encrypted_git_plots is retired; run scripts/make_review_figures.py"
    )

def main():
    os.makedirs(FIG, exist_ok=True)
    for name, fn in (
        ("realrepo-baseline-plots.tex", realrepo_plots),
        ("additive-baseline-plots.tex", additive_plots),
    ):
        text = fn()
        path = os.path.join(FIG, name)
        with open(path, "w") as fh:
            fh.write(text)
        print("wrote paper/figures/" + name)


if __name__ == "__main__":
    main()
