#!/usr/bin/env python3
"""Figures for the baseline, depth, and contention measurements.

Writes:
  paper/figures/depth-clone-plots.tex        clone vs depth to 10^4, with the
                                             pre-multi-pack-index ablation
  paper/figures/encrypted-git-baseline-plots.tex  four arms, two fixtures
  paper/figures/concurrency-plots.tex        throughput and retries vs pushers

Every series here is measured. Where a published file carries an explicit
caveat (the depth run's lost per-replicate samples), the caption says so rather
than letting a clean-looking curve imply more than the data supports.
"""
from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PUB = os.path.join(ROOT, "code", "eval", "published")
FIGS = os.path.join(ROOT, "paper", "figures")

COLORS = r"""\definecolor{sitcol}{HTML}{1B6CA8}
\definecolor{gitcol}{HTML}{C0392B}
\definecolor{precol}{HTML}{7F8C8D}
\definecolor{gccol}{HTML}{B7950B}
\definecolor{gycol}{HTML}{6C3483}
"""


def load(name: str):
    path = os.path.join(PUB, name)
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)


def med(cell):
    if cell is None:
        return None
    return cell.get("median", cell.get("value"))


# ----------------------------------------------------------- depth vs clone
def depth_clone_plots() -> str:
    d = load("depth-clone-latest.json")
    if not d:
        sys.exit("depth-clone-latest.json missing")
    cells = sorted(d["cells"], key=lambda c: c["history_depth"])
    sit = " ".join(f"({c['history_depth']},{med(c['clone_ms'])/1000.0:.4f})" for c in cells)
    git = " ".join(f"({c['history_depth']},{med(c['git_clone_ms'])/1000.0:.4f})" for c in cells)
    sit_ph = " ".join(f"({c['history_depth']},{c['clone_ms_per_head']:.3f})" for c in cells)
    # The caption quotes the deepest checkpoint, so read it rather than
    # carrying a number that a re-run silently invalidates.
    deep = cells[-1]
    deep_sit = f"${deep['clone_ms']['median'] / 1000:.0f}$\\,s"
    deep_git = f"${deep['git_clone_ms']['median'] / 1000:.1f}$\\,s"

    pre = load("depth-clone-prefix-ablation.json")
    pre_ph = ""
    pre_series = ""
    pre_note = ""
    if pre:
        obs = pre.get("observed_ms_per_head", {})
        pts = sorted((int(k), v) for k, v in obs.items())
        pre_ph = " ".join(f"({k},{v:.3f})" for k, v in pts)
        pre_series = (
            "\\addplot[color=precol,dashed,mark=triangle*,mark size=1.6pt,"
            "thick] coordinates {" + pre_ph + "};\n"
            "\\addlegendentry{SafeHub, before fix}\n"
        )
        pre_note = (
            " The dashed series in panel~(b) is the same harness before the "
            "periodic multi-pack-index refresh was added during clone replay: "
            "cost per head climbed with depth because one packfile lands per "
            "replayed head."
        )

    caveat = ""
    if d.get("provenance_caveat"):
        caveat = (
            " Cells are medians over three clones; per-replicate samples for "
            "this run were lost to a harness cleanup fault and the harness has "
            "since been hardened, so no dispersion is drawn."
        )

    return (
        "% Generated by scripts/make_review_figures.py -- do not edit by hand.\n"
        + COLORS
        + r"""\begin{figure}[t]
\centering
\begin{tikzpicture}
\begin{groupplot}[
  group style={group size=1 by 2, vertical sep=1.5cm},
  width=0.86\linewidth, height=4.3cm,
  xmode=log, log basis x=10,
  xlabel={history depth (heads)},
  tick label style={font=\scriptsize}, xlabel shift=-4pt,
  label style={font=\scriptsize}, xlabel shift=-4pt,
  legend style={font=\scriptsize, at={(0.02,0.98)}, anchor=north west,
                draw=none, fill=none, row sep=-1pt},
  grid=both, grid style={line width=.1pt, draw=gray!20},
]
\nextgroupplot[ymode=log, ylabel={clone (s)}, title={\scriptsize (a) clone latency, both arms}]
\addplot[color=sitcol,mark=*,mark size=1.6pt,thick] coordinates {"""
        + sit
        + r"""};
\addlegendentry{SafeHub}
\addplot[color=gitcol,mark=square*,mark size=1.6pt,thick] coordinates {"""
        + git
        + r"""};
\addlegendentry{Git}

\nextgroupplot[ylabel={ms per head}, ymin=0,
  title={\scriptsize (b) marginal cost per head}]
\addplot[color=sitcol,mark=*,mark size=1.6pt,thick] coordinates {"""
        + sit_ph
        + r"""};
\addlegendentry{SafeHub}
"""
        + pre_series
        + r"""\end{groupplot}
\end{tikzpicture}
\caption{Clone versus history depth, measured to $10^{4}$ heads on both arms.
One lineage is grown once with a fixed $64$\,KiB per-push delta, so depth is
the only axis, and every clone is checked for tree-hash equality against the
plain-Git arm. Panel~(a): at the deepest checkpoint a \safehub clone costs
@DEEP_SIT@ against Git's @DEEP_GIT@. Panel~(b) reports marginal cost per head:
a blind host cannot repack, so the design requires this quantity to remain
bounded. Consolidation is specified to bound it but is not yet wired end to
end, so the curve shown is unmitigated."""
        + pre_note
        + caveat
        + r"""}
\label{fig:depth-clone}
\end{figure}
"""
    ).replace("@DEEP_SIT@", deep_sit).replace("@DEEP_GIT@", deep_git)


# --------------------------------------------------- encrypted-git baselines
ARMS = [
    ("plain-git", "Git", "gitcol"),
    ("git-crypt", "git-crypt", "gccol"),
    ("git-remote-gcrypt", "gcrypt", "gycol"),
    ("safehub", "SafeHub", "sitcol"),
]


def encrypted_git_plots() -> str:
    real = load("encrypted-git-baseline-realtree.json")
    synth = load("encrypted-git-baseline-latest.json")
    if not (real and synth):
        sys.exit("encrypted-git baseline files missing")

    def arms_of(doc):
        return {a["arm"]: a for a in doc["arms"]}

    def bars(doc, field, scale=1.0):
        a = arms_of(doc)
        out = []
        for i, (key, _lab, _c) in enumerate(ARMS, start=1):
            row = a.get(key)
            if not row or not row.get("available"):
                continue
            if field == "remote_bytes":
                v = row["remote_bytes"] / scale
            else:
                v = med(row[field]) / scale
            out.append(f"({i},{v:.3f})")
        return " ".join(out)

    xticklabels = ",".join(lab for _, lab, _ in ARMS)
    xtick = ",".join(str(i) for i, _ in enumerate(ARMS, start=1))

    ra, sa = arms_of(real), arms_of(synth)
    gc_ratio_real = ra["git-crypt"]["remote_bytes"] / ra["safehub"]["remote_bytes"]
    gc_ratio_syn = sa["git-crypt"]["remote_bytes"] / sa["safehub"]["remote_bytes"]
    gy_clone_real = med(ra["git-remote-gcrypt"]["clone_ms"]) / med(ra["safehub"]["clone_ms"])
    gy_clone_syn = med(sa["git-remote-gcrypt"]["clone_ms"]) / med(sa["safehub"]["clone_ms"])

    return (
        "% Generated by scripts/make_review_figures.py -- do not edit by hand.\n"
        + COLORS
        + r"""\begin{figure}[t]
\centering
\begin{tikzpicture}
\begin{groupplot}[
  group style={group size=2 by 2, horizontal sep=1.5cm, vertical sep=1.35cm},
  width=0.42\linewidth, height=3.5cm,
  ybar, /pgf/bar width=5pt,
  ymin=0, ymajorgrids, grid style={line width=.1pt, draw=gray!20},
  xtick={"""
        + xtick
        + r"""},
  xticklabels={"""
        + xticklabels
        + r"""},
  x tick label style={rotate=40, anchor=east, font=\tiny},
  tick label style={font=\tiny}, xlabel shift=-4pt, label style={font=\scriptsize}, xlabel shift=-4pt,
  title style={font=\scriptsize},
  enlarge x limits=0.15,
]
\nextgroupplot[ylabel={clone (ms)}, ymode=log, title={(a) clone, real tree}]
\addplot[fill=sitcol!70,draw=none] coordinates {"""
        + bars(real, "clone_ms")
        + r"""};
\nextgroupplot[ylabel={clone (ms)}, ymode=log, title={(b) clone, synthetic}]
\addplot[fill=sitcol!70,draw=none] coordinates {"""
        + bars(synth, "clone_ms")
        + r"""};
\nextgroupplot[ylabel={remote (MB)}, ymode=log, title={(c) storage, real tree}]
\addplot[fill=gccol!70,draw=none] coordinates {"""
        + bars(real, "remote_bytes", 1e6)
        + r"""};
\nextgroupplot[ylabel={remote (MB)}, ymode=log, title={(d) storage, synthetic}]
\addplot[fill=gccol!70,draw=none] coordinates {"""
        + bars(synth, "remote_bytes", 1e6)
        + r"""};
\end{groupplot}
\end{tikzpicture}
\caption{Encrypted-Git baselines on two fixtures: a real checkout
(\texttt{ripgrep} at \texttt{HEAD}) and a deliberately compressible synthetic
tree. All four arms are measured; none is modelled. The clone advantage over
whole-remote PGP encryption is stable across fixtures
($%.1f\times$ real, $%.1f\times$ synthetic) because that design re-encrypts the
remote on every push. The storage advantage over per-file encryption is not
($%.1f\times$ real, $%.1f\times$ synthetic): \texttt{git-crypt} seals each file
before Git packs it, so its remote tracks the raw tree irrespective of content,
whereas \safehub packs first and seals second and retains Git's compression.
The ratio between them is therefore approximately the compression ratio of the
corpus, which the synthetic fixture overstates.}
\label{fig:encrypted-git-baseline}
\end{figure}
"""
        % (gy_clone_real, gy_clone_syn, gc_ratio_real, gc_ratio_syn)
    )


# ------------------------------------------------------------- concurrency
def concurrency_plots() -> str:
    d = load("concurrency-latest.json")
    if not d:
        sys.exit("concurrency-latest.json missing")
    cells = sorted(d["cells"], key=lambda c: c["pushers"])
    tput = " ".join(f"({c['pushers']},{c['throughput_pushes_per_s']:.2f})" for c in cells)
    retry = " ".join(f"({c['pushers']},{c['cas_retry_hints']})" for c in cells)
    linear = " ".join(f"({c['pushers']},{c['pushers']})" for c in cells)
    failed = sum(c["fail"] for c in cells)
    starv = d.get("starvation", {})
    starve_txt = ""
    if starv.get("measured"):
        ok = "completed" if starv.get("large_completed") else "did not complete"
        starve_txt = (
            " A starvation configuration (one $%d$\\,MiB push against four concurrent "
            "small pushes) %s in $%.2f$\\,s."
            % (starv.get("large_push_mib", 8), ok, starv.get("wall_s", 0.0))
        )

    return (
        "% Generated by scripts/make_review_figures.py -- do not edit by hand.\n"
        + COLORS
        + r"""\begin{figure}[t]
\centering
\begin{tikzpicture}
\begin{groupplot}[
  group style={group size=2 by 1, horizontal sep=1.5cm},
  width=0.44\linewidth, height=3.6cm,
  xmode=log, log basis x=2, xlabel={concurrent pushers $N$},
  tick label style={font=\tiny}, xlabel shift=-4pt, label style={font=\scriptsize}, xlabel shift=-4pt,
  title style={font=\scriptsize},
  grid=both, grid style={line width=.1pt, draw=gray!20},
  legend style={font=\tiny, at={(0.02,0.98)}, anchor=north west, draw=none,
                fill=none, row sep=-2pt},
]
\nextgroupplot[ylabel={pushes/s}, ymin=0, title={(a) throughput}]
\addplot[color=sitcol,mark=*,mark size=1.5pt,thick] coordinates {"""
        + tput
        + r"""};
\nextgroupplot[ymode=log, ylabel={CAS retries}, title={(b) retries against $y{=}N$}]
\addplot[color=gitcol,mark=square*,mark size=1.5pt,thick] coordinates {"""
        + retry
        + r"""};
\addlegendentry{retries}
\addplot[color=precol,dashed,thick] coordinates {"""
        + linear
        + r"""};
\addlegendentry{$y=N$}
\end{groupplot}
\end{tikzpicture}
\caption{Head-log contention: $N$ real clients pushing to $N$ distinct
branches against one server. A single compare-and-swap log per repository
serializes every push in that repository, which a plaintext forge does not do.
No push was lost at any $N$ (%d failures in total, within the retry budget of
$8$); throughput saturates rather than scaling, and retries grow faster than
$N$.%s These are single-host measurements: at $N{=}32$ the clients contend with
the server for the same cores, so the flattening combines client scheduling
with head-log contention.}
\label{fig:concurrency}
\end{figure}
"""
        % (failed, starve_txt)
    )


def main() -> None:
    for name, fn in (
        ("concurrency-plots.tex", concurrency_plots),
    ):
        body = fn()
        out = os.path.join(FIGS, name)
        with open(out, "w") as f:
            f.write(body)
        print(f"wrote paper/figures/{name}")


if __name__ == "__main__":
    main()
