#!/usr/bin/env python3
"""Generate the six-arm sweep figures and tables.

Reads the published sweep artifacts and writes LaTeX into paper/figures/.
Everything is a measured cell; nothing is modelled. An arm with no cell for a
point gets a dash, never a zero, because an operation a design cannot express
and an operation that costs nothing are opposite claims.
"""
from __future__ import annotations

import glob
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
S1 = ROOT / "code/eval/published/e13-full-20260820"
S2 = ROOT / "code/eval/published/e13-ops-20260820"
FIG = ROOT / "paper/figures"

# Display order: ours first, then the closest peers, then the rest.
ARMS = ["safehub", "git", "sgitchar", "sgitline", "gitcrypt", "gcrypt"]
LABEL = {"safehub": r"\safehub", "git": "git", "sgitchar": "SGitChar",
         "sgitline": "SGitLine", "gitcrypt": "git-crypt", "gcrypt": "gcrypt"}


def rows(pat: str):
    out = []
    for p in glob.glob(str(pat)):
        out += [json.loads(l) for l in open(p) if l.strip()]
    return out


def cell(rs, arm, point, key, sub="median"):
    r = next((x for x in rs if x.get("arm") == arm and x.get("point") == point), None)
    if not r:
        return None
    v = r.get(key)
    if isinstance(v, dict):
        return v.get(sub)
    return v


def fmt(v, scale=1.0, prec=0):
    """Bytes at a readable magnitude. A dash for absent, never a zero."""
    if v is None:
        return "--"
    v = v / scale
    if v >= 1e6:
        return f"{v/1e6:.2f}\\,M"
    if v >= 1e4:
        return f"{v/1e3:.0f}\\,k"
    return f"{v:.{prec}f}"


def wire_table() -> str:
    """A2: the experiment that separates cost-per-edit from cost-per-file."""
    rs = rows(S1 / "A2-filesz-rows.jsonl")
    pts = sorted({r["point"] for r in rs})
    head = " & ".join(f"{p}" if p < 1024 else f"{p//1024}\\,M" for p in pts)
    lines = [
        "% Generated by scripts/make_sweep_figures.py -- do not edit by hand.",
        r"\begin{table}[t]", r"\centering",
        r"\caption{Bytes one \textbf{1\,KiB edit} puts on the wire as the edited"
        r" file grows, measured against the remote tip before the push. git and"
        r" SGitChar track the \emph{edit}; git-crypt and SGitLine track the"
        r" \emph{file}. \Safehub and gcrypt expose no readable ref map, so no"
        r" thin pack can be measured for them.}",
        r"\label{tab:sweep-wire}", r"\footnotesize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{@{}l" + "r" * len(pts) + r"@{}}", r"\toprule",
        r"file size (KiB) & " + head + r" \\", r"\midrule",
    ]
    for a in ARMS:
        vals = [cell(rs, a, p, "wire_bytes_per_update") for p in pts]
        if all(v is None for v in vals):
            continue
        lines.append(LABEL[a] + " & " + " & ".join(fmt(v) for v in vals) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


def ops_table() -> str:
    """Sweep 2: the operations, against history depth."""
    rs = rows(S2 / "ops-l*.jsonl")
    pts = sorted({r["point"] for r in rs})
    ops = ["forcepush", "rotate", "consolidate"]
    lines = [
        "% Generated by scripts/make_sweep_figures.py -- do not edit by hand.",
        r"\begin{table}[t]", r"\centering",
        r"\caption{Force-push, rotate and consolidation against history depth."
        r" A system absent from a block does not express that operation:"
        r" force-push is undefined for the SGit designs, whose ciphertext"
        r" repository only appends, so a host cannot tell a rewrite from an"
        r" ordinary push; only \safehub has rotate and consolidation.}",
        r"\label{tab:sweep-ops}", r"\footnotesize",
        r"\setlength{\tabcolsep}{3.5pt}",
        r"\begin{tabular}{@{}ll" + "r" * len(pts) + r"@{}}", r"\toprule",
        r"operation & system & " + " & ".join(str(p) for p in pts) + r" \\",
        r"\midrule",
    ]
    for op in ops:
        sub = [r for r in rs if r.get("op") == op]
        first = True
        for a in ARMS:
            vals = [cell(sub, a, p, "op_ms") for p in pts]
            if all(v is None for v in vals):
                continue   # undefined for this arm; the caption says which
            name = f"\\texttt{{{op}}}" if first else ""
            first = False
            lines.append(f"{name} & {LABEL[a]} & " + " & ".join(fmt(v) for v in vals) + r" \\")
        lines.append(r"\addlinespace")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


def depth_plot() -> str:
    """C: clone against history depth, log-log, six arms."""
    rs = rows(S1 / "C-depth-rows.jsonl")
    pts = sorted({r["point"] for r in rs})
    lines = [
        "% Generated by scripts/make_sweep_figures.py -- do not edit by hand.",
    ]
    lines += _defs()
    lines += [
        r"\begin{figure}[t]", r"\centering",
        r"\begin{tikzpicture}",
        r"\begin{axis}[width=\columnwidth,height=5.2cm,xmode=log,ymode=log,",
        r"  xlabel={history depth (heads)},ylabel={clone (ms)},",
        r"  legend style={font=\scriptsize,at={(0.02,0.98)},anchor=north west,",
        r"    legend columns=2,draw=none,fill opacity=0.8},",
        r"  grid=major,grid style={gray!20},tick label style={font=\scriptsize},",
        r"  label style={font=\small},xlabel shift=-4pt]",
    ]
    for a in ARMS:
        pairs = [(p, cell(rs, a, p, "clone_ms")) for p in pts]
        pairs = [(p, v) for p, v in pairs if v]
        if len(pairs) < 2:
            continue
        coords = " ".join(f"({p},{v:.0f})" for p, v in pairs)
        lines.append(f"\\addplot[color={COLOR[a][0]},mark={MARK[a]},"
                     f"mark size=1.3pt,thick] coordinates {{{coords}}};")
        lines.append(f"\\addlegendentry{{{LABEL[a]}}}")
    lines += [
        r"\end{axis}", r"\end{tikzpicture}",
        r"\caption{Clone time against the number of commits in the history, six systems. Every clone is unlocked and its contents compared against the source inside the timer: a gcrypt clone exits successfully having checked out nothing, and git-crypt leaves ciphertext in the working tree until unlocked.}",
        r"\label{fig:sweep-depth}", r"\end{figure}",
    ]
    return "\n".join(lines) + "\n"


# Arm colours match the rest of the paper's plots.
COLOR = {"safehub": ("sitcol", "1B6CA8"), "git": ("gitcol", "C0392B"),
         "sgitchar": ("sccol", "1E8449"), "sgitline": ("slcol", "E67E22"),
         "gitcrypt": ("gccol", "B7950B"), "gcrypt": ("gycol", "6C3483")}
MARK = {"safehub": "*", "git": "square*", "sgitchar": "triangle*",
        "sgitline": "diamond*", "gitcrypt": "o", "gcrypt": "pentagon*"}


def _defs() -> list:
    return [rf"\definecolor{{{n}}}{{HTML}}{{{h}}}" for n, h in COLOR.values()]


def _panel(rs, pts, key, xlabel, ylabel, first=False, ymode="log",
           leg="sweeppayleg", legcols=6) -> list:
    """One groupplot panel: every arm that has a measured series."""
    opts = [f"xlabel={{{xlabel}}}", f"ylabel={{{ylabel}}}",
            "xmode=log", f"ymode={ymode}"]
    if first:
        opts += [f"legend to name={leg}", f"legend columns={legcols}"]
    out = [r"\nextgroupplot[" + ",".join(opts) + "]"]
    for a in ARMS:
        pairs = [(p, cell(rs, a, p, key)) for p in pts]
        pairs = [(p, v) for p, v in pairs if v]
        if len(pairs) < 2:
            continue
        coords = " ".join(f"({p},{v:.0f})" for p, v in pairs)
        out.append(f"\\addplot[color={COLOR[a][0]},mark={MARK[a]},"
                   f"mark size=1.3pt,thick] coordinates {{{coords}}};")
        if first:
            out.append(f"\\addlegendentry{{{LABEL[a]}}}")
    return out


def payload_plot() -> str:
    """A1, A3, D, E: the four byte axes, all six arms.

    Storage growth is the metric every arm admits. Thin-pack wire bytes exist
    only where the remote exposes a readable ref map, which rules out \\safehub
    and gcrypt, so plotting wire bytes here would silently drop two arms.
    """
    a1 = rows(S1 / "A1-delta-rows.jsonl")
    a3 = rows(S1 / "A3-nfiles-rows.jsonl")
    d = rows(S1 / "D-updates-rows.jsonl")
    e = rows(S1 / "E-revs-rows.jsonl")
    pt = lambda rs: sorted({r["point"] for r in rs})
    lines = ["% Generated by scripts/make_sweep_figures.py -- do not edit by hand."]
    lines += _defs()
    lines += [
        r"\begin{figure}[t]", r"\centering", r"\begin{tikzpicture}",
        r"\begin{groupplot}[group style={group size=2 by 2,"
        r"horizontal sep=0.7cm,vertical sep=1.45cm},"
        r"width=0.55\columnwidth,height=4.3cm,grid=major,"
        r"grid style={gray!20},tick label style={font=\tiny},"
        r"label style={font=\scriptsize},xlabel shift=-4pt,"
        r"legend style={font=\scriptsize,draw=none,fill=none,column sep=1.4ex}]",
    ]
    lines += _panel(a1, pt(a1), "remote_growth_per_update",
                    r"edit size (KiB)", r"growth/update (B)", first=True,
                    legcols=3)
    lines += _panel(a3, pt(a3), "remote_growth_per_update",
                    r"files touched", r"growth/update (B)")
    lines += _panel(d, pt(d), "stored_growth_per_version",
                    r"versions", r"growth/version (B)")
    lines += _panel(e, pt(e), "stored_growth_bytes",
                    r"revisions of one file", r"total growth (B)")
    lines += [
        r"\end{groupplot}", r"\end{tikzpicture}", r"\\[2pt]",
        r"\ref{sweeppayleg}",
        r"\caption{How much storage the server gains from one update, as four different quantities grow: (a) the size of the edit, (b) the number of files one edit touches, (c) the number of versions pushed, and (d) repeated edits to a single file. \Safehub and plain Git follow the \emph{edit}; git-crypt and SGitLine re-encrypt whole files, so they follow file size and file count instead. Storage growth is the measure used because it is the only one all six systems permit---wire bytes need a readable ref map, which \safehub and gcrypt do not expose.}",
        r"\label{fig:sweep-payload}", r"\end{figure}",
    ]
    return "\n".join(lines) + "\n"


def scale_table() -> str:
    """B: push, clone and storage against repository size, six arms."""
    rs = rows(S1 / "B-size-rows-merged.jsonl")
    pts = sorted({r["point"] for r in rs})
    lines = [
        "% Generated by scripts/make_sweep_figures.py -- do not edit by hand.",
        r"\begin{table}[t]", r"\centering",
        r"\caption{Push, clone and storage growth against repository size"
        r" (E13-B), median of five repetitions (gcrypt three). Push carries a"
        r" fixed $50$\,KiB delta, so its trend is the cost of \emph{carrying}"
        r" that delta against a larger repository, not of larger content."
        r" Every clone is unlocked and compared against its source content"
        r" inside the timer.}",
        r"\label{tab:sweep-scale}", r"\footnotesize",
        r"\setlength{\tabcolsep}{3.5pt}",
        r"\begin{tabular}{@{}l" + "r" * len(pts) + r"@{}}", r"\toprule",
        r"repo size (MB) & " + " & ".join(str(p) for p in pts) + r" \\",
        r"\midrule",
    ]
    for key, title, unit in [("push_ms", "push", "ms"),
                             ("clone_ms", "clone", "ms"),
                             ("stored_growth_bytes", "storage growth", "B")]:
        lines.append(r"\multicolumn{" + str(len(pts) + 1) +
                     r"}{@{}l@{}}{\emph{" + title + f" ({unit})" + r"}} \\")
        for a in ARMS:
            vals = [cell(rs, a, p, key) for p in pts]
            if all(v is None for v in vals):
                continue
            lines.append(r"\quad " + LABEL[a] + " & " +
                         " & ".join(fmt(v) for v in vals) + r" \\")
        lines.append(r"\addlinespace")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


def ops_plot() -> str:
    """The five operations the sweeps cover for all six arms, plus storage.

    Panels (a)-(c) vary repository size (E13-B); (d)-(f) vary history depth
    (E13-OPS). The axes differ because no single sweep varies both, so each
    panel is labelled with the axis it was measured on.
    """
    b = rows(S1 / "B-size-rows-merged.jsonl")
    o = rows(S2 / "ops-l*.jsonl")
    bp = sorted({r["point"] for r in b})
    op_ = sorted({r["point"] for r in o})
    lines = ["% Generated by scripts/make_sweep_figures.py -- do not edit by hand."]
    lines += _defs()
    lines += [
        r"\begin{figure*}[t]", r"\centering", r"\begin{tikzpicture}",
        r"\begin{groupplot}[group style={group size=3 by 2,"
        r"horizontal sep=1.3cm,vertical sep=1.4cm},"
        r"width=0.28\textwidth,height=0.21\textwidth,grid=major,"
        r"grid style={gray!20},tick label style={font=\tiny},"
        r"label style={font=\tiny},xlabel shift=-4pt,"
        r"legend style={font=\scriptsize,draw=none,fill=none,column sep=1.4ex}]",
    ]
    lines += _panel(b, bp, "push_ms", r"repo (MB)", r"push (ms)",
                    first=True, leg="sweepopsleg")
    lines += _panel(b, bp, "clone_ms", r"repo (MB)", r"clone (ms)")
    lines += _panel(b, bp, "stored_growth_bytes", r"repo (MB)", r"growth (B)")
    for op, lab in (("pull", "pull"), ("merge", "merge"), ("rebase", "rebase")):
        sub = [r for r in o if r.get("op") == op]
        lines += _panel(sub, op_, "op_ms", r"depth (heads)", lab + r" (ms)")
    lines += [
        r"\end{groupplot}", r"\end{tikzpicture}", r"\\[2pt]",
        r"\ref{sweepopsleg}",
        r"\caption{Six systems, one transport. The top row holds the pushed payload at $50$\,KiB and the history at one head, varying only the size of the repository the push lands in: push \emph{ought} to be flat there, so the row is a control that separates systems whose per-push cost is proportional to the repository from those where it is not. Git and \safehub are flat to $1.1\times$ across a $40\times$ range; gcrypt re-encrypts the whole remote each time, and the SGit designs read and rewrite a whole-tree snapshot on every push, so all three scale with it. Clone and stored size depend on repository size by construction. The bottom row varies history depth instead. \Safehub is the fastest system on push, pull, merge and rebase and flat on both axes, and its storage growth matches plain Git's because it seals the packfile Git has already compressed. Clone is the exception: a host that cannot read a repository cannot repack it, so cost follows push count.}",
        r"\label{fig:sweep-ops}", r"\end{figure*}",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    FIG.mkdir(parents=True, exist_ok=True)
    for name, gen in [("sweep-wire-table.tex", wire_table),
                      ("sweep-ops-table.tex", ops_table),
                      ("sweep-depth-plot.tex", depth_plot),
                      ("sweep-payload-plot.tex", payload_plot),
                      ("sweep-ops-plot.tex", ops_plot)]:
        (FIG / name).write_text(gen())
        print(f"  wrote paper/figures/{name}")


if __name__ == "__main__":
    main()
