#!/usr/bin/env python3
"""Emit SafeHub vs Git depth×delta figures from published E02 JSON.

Requires measured git_push_ms / git_clone_ms on every plotted cell.

Writes:
  paper/figures/depth-delta-plot-body.tex
  paper/figures/depth-delta-plots.tex
  paper/figures/depth-delta-standalone.tex
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    ROOT, "code/eval/published/depth-delta-latest.json")
FIG = os.path.join(ROOT, "paper", "figures")


def load():
    d = json.load(open(SRC))
    cells = [c for c in d["cells"] if c.get("status") == "measured"]
    arm_a = sorted(
        (c for c in cells if c["arm"] == "fixed-delta-varying-depth"),
        key=lambda c: c["history_depth"])
    arm_b = sorted(
        (c for c in cells if c["arm"] == "fixed-depth-varying-delta"),
        key=lambda c: c["per_push_delta_kib"])
    for label, rows in (("Arm A", arm_a), ("Arm B", arm_b)):
        missing = [
            c for c in rows
            if "git_push_ms" not in c or "git_clone_ms" not in c
        ]
        if missing:
            keys = [
                f"depth={c['history_depth']}/delta={c['per_push_delta_kib']}"
                for c in missing
            ]
            sys.exit(f"missing measured Git baseline in {label}: " +
                     ", ".join(keys))
    return d, arm_a, arm_b


def coords(rows, xfn, yfn, nd=1):
    return " ".join(f"({xfn(c)},{round(yfn(c), nd)})" for c in rows)


def body(arm_b):
    """Delta arm only.

    The depth arm that used to occupy panels (a)-(b) held the per-push delta at
    64 KiB and varied depth over 5-100 heads, which is the same experiment
    fig:depth-clone runs to 10^4 on the post-fix build. Plotting both told the
    depth story twice at inconsistent ranges, so the depth arm is measured there
    and this figure carries the delta axis alone.
    """
    b_sh_push = coords(arm_b, lambda c: c["per_push_delta_kib"],
                       lambda c: c["push_ms"]["median"])
    b_git_push = coords(arm_b, lambda c: c["per_push_delta_kib"],
                        lambda c: c["git_push_ms"]["median"])
    b_sh_clone = coords(arm_b, lambda c: c["per_push_delta_kib"],
                        lambda c: c["clone_ms"]["median"])
    b_git_clone = coords(arm_b, lambda c: c["per_push_delta_kib"],
                         lambda c: c["git_clone_ms"]["median"])
    depth_b = arm_b[0]["history_depth"] if arm_b else 20

    tpl = r"""% Generated by scripts/make_depth_delta_figures.py -- do not edit by hand.
\definecolor{sitcol}{HTML}{1B6CA8}
\definecolor{gitcol}{HTML}{C0392B}
\begin{tikzpicture}
\begin{groupplot}[
  group style={group size=1 by 2, vertical sep=1.0cm},
  width=0.86\linewidth, height=3.9cm,
  xmode=log, log basis x=2, xmin=8, xmax=1200,
  xtick={16,64,256,1024}, xticklabels={16,64,256,1024}, ymin=0,
  tick label style={font=\scriptsize},
  label style={font=\scriptsize},
  legend style={font=\scriptsize, at={(0.02,0.98)}, anchor=north west,
                draw=none, fill=none, row sep=-1pt},
  grid=both, grid style={line width=.1pt, draw=gray!20},
]

\nextgroupplot[ylabel={push (ms)},
  title={\scriptsize (a) push, fixed depth $@DEPTH_B@$}]
\addplot[thick, sitcol, mark=*,       mark size=1.3] coordinates {@B_SH_PUSH@};
\addlegendentry{SafeHub}
\addplot[thick, gitcol, mark=square*, mark size=1.3] coordinates {@B_GIT_PUSH@};
\addlegendentry{Git}

\nextgroupplot[ylabel={clone (ms)}, xlabel={per-push delta (KiB)},
  title={\scriptsize (b) clone, fixed depth $@DEPTH_B@$}]
\addplot[thick, sitcol, mark=*,       mark size=1.3] coordinates {@B_SH_CLONE@};
\addplot[thick, gitcol, mark=square*, mark size=1.3] coordinates {@B_GIT_CLONE@};

\end{groupplot}
\end{tikzpicture}
"""
    for key, val in (
        ("B_SH_PUSH", b_sh_push), ("B_GIT_PUSH", b_git_push),
        ("B_SH_CLONE", b_sh_clone), ("B_GIT_CLONE", b_git_clone),
        ("DEPTH_B", str(depth_b)),
    ):
        tpl = tpl.replace("@" + key + "@", val)
    return tpl


def figure(d, arm_b):
    depth_b = arm_b[0]["history_depth"] if arm_b else 20
    return r"""% Generated by scripts/make_depth_delta_figures.py -- do not edit by hand.
\begin{figure}[t]
\centering
\input{figures/depth-delta-plot-body}
\caption{SafeHub versus plain Git as the per-push delta varies at fixed
history depth $@DEPTH_B@$ (median localhost E2E latency; byte-identical
source-shaped commits). Holding depth constant isolates the delta axis, which
the repository-size sweep of \cref{fig:parity} confounds with depth; the
complementary depth axis is measured to $10^{4}$ heads in
\cref{fig:depth-clone}. Git is served by a local \texttt{git daemon} from its
\texttt{gc}-packed bare repository, the same state the size sweep reports.}
\label{fig:depth-delta}
\end{figure}
""".replace("@DEPTH_B@", str(depth_b))


def standalone():
    return r"""\documentclass[tikz,border=3mm]{standalone}
\usepackage{pgfplots}
\usepgfplotslibrary{groupplots}
\usetikzlibrary{positioning}
\pgfplotsset{compat=1.18}
\begin{document}
\input{figures/depth-delta-plot-body}
\end{document}
"""


def main():
    d, _arm_a, arm_b = load()
    if not arm_b:
        sys.exit("need measured Arm B (fixed-depth-varying-delta) cells in " + SRC)
    os.makedirs(FIG, exist_ok=True)
    for name, text in (
        ("depth-delta-plot-body.tex", body(arm_b)),
        ("depth-delta-plots.tex", figure(d, arm_b)),
        ("depth-delta-standalone.tex", standalone()),
    ):
        with open(os.path.join(FIG, name), "w") as fh:
            fh.write(text)
        print("wrote paper/figures/" + name)
    print(f"Arm B deltas: {', '.join(str(c['per_push_delta_kib']) for c in arm_b)} KiB")
    attr = d.get("attribution", {})
    print("SafeHub push ms per extra KiB:",
          attr.get("push_ms_per_extra_kib_of_delta"))
    print("Git push ms per extra KiB:",
          attr.get("git_push_ms_per_extra_kib_of_delta"))


if __name__ == "__main__":
    main()
